services:
  api:
    build: 
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: poetry run uvicorn flasco.main:app --host 0.0.0.0 --port 8000 --reload
    network_mode: host