services:
  api:
    build: 
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      - DEBUG=true
    command: ["sh", "-c", "poetry run python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn flasco.main:app --host 0.0.0.0 --port 8000"]
    network_mode: host
