"""add type to user table

Revision ID: 7f52bf4d09f6
Revises: a1d4a58297f7
Create Date: 2025-06-08 22:44:01.032401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f52bf4d09f6'
down_revision: Union[str, None] = 'a1d4a58297f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('tipo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tipo')
    # ### end Alembic commands ###
