"""migration inicial

Revision ID: df23133e6bc0
Revises: 
Create Date: 2025-05-31 18:20:06.836784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df23133e6bc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('instituicao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aluno',
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('curso', sa.Enum('TECNICO_DE_INFORMATICA', 'ENGENHARIA_DE_SOFTWARE', 'ENGENHARIA_DE_COMPUTACAO', 'SISTEMAS_DE_INFORMACAO', 'ANALISE_DESENVOLVIMENTO_DE_SISTEMAS', 'ENGENHARIA_DE_INFORMACAO', 'CIENCIA_DA_COMPUTACAO', name='curso_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('professor',
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('formacao', sa.Enum('MESTRE', 'DOUTOR', 'PHD', name='formacao_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('modulo',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('id_professor_criador', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_modulo', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_professor_criador'], ['professor.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_modulo')
    )
    op.create_table('videoaula',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('duracao', sa.Time(), nullable=False),
    sa.Column('videoaula_path', sa.String(length=255), nullable=False),
    sa.Column('id_professor', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('qntd_curtidas', sa.Integer(), nullable=False),
    sa.Column('id_video', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_video')
    )
    op.create_table('anexo',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('anexo_path', sa.String(length=255), nullable=False),
    sa.Column('id_video', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_anexo', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_video'], ['videoaula.id_video'], ),
    sa.PrimaryKeyConstraint('id_anexo'),
    sa.UniqueConstraint('anexo_path')
    )
    op.create_table('armazena_um',
    sa.Column('id_video', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_modulo', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_video'], ['videoaula.id_video'], ),
    sa.PrimaryKeyConstraint('id_video', 'id_modulo')
    )
    op.create_table('comentario',
    sa.Column('conteudo', sa.String(length=400), nullable=False),
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_video', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_resposta', sa.Uuid(as_uuid=32), nullable=True),
    sa.Column('id_comentario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_resposta'], ['comentario.id_comentario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_video'], ['videoaula.id_video'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('curte_um',
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_video', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_video'], ['videoaula.id_video'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_video')
    )
    op.create_table('favorita_um',
    sa.Column('id_usuario', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_modulo', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_modulo')
    )
    op.create_table('se_matricula',
    sa.Column('id_aluno', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('id_modulo', sa.Uuid(as_uuid=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id_modulo'], ),
    sa.PrimaryKeyConstraint('id_aluno', 'id_modulo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('se_matricula')
    op.drop_table('favorita_um')
    op.drop_table('curte_um')
    op.drop_table('comentario')
    op.drop_table('armazena_um')
    op.drop_table('anexo')
    op.drop_table('videoaula')
    op.drop_table('modulo')
    op.drop_table('professor')
    op.drop_table('aluno')
    op.drop_table('usuario')
    # ### end Alembic commands ###
