from flasco.models.aluno import Aluno
from flasco.models.anexo import Anexo
from flasco.models.armazena_um import ArmazenaUm
from flasco.models.comentario import Comentario
from flasco.models.curte_um import CurteUm
from flasco.models.favorita_um import FavoritaUm
from flasco.models.modulo import Modulo
from flasco.models.professor import Professor
from flasco.models.se_matricula import SeMatricula
from flasco.models.usuario import Usuario
from flasco.models.video import Video